HEAD:
  mixed-port: 7890
  allow-lan: false 
  mode: rule
  log-level: none
  external-controller: :9090
  dns:
    enable: true
    listen: 0.0.0.0:1053
    prefer-h3: true
    default-nameserver:
    - 223.5.5.5
    nameserver-policy:
      geosite:gfw,geolocation-!cn:
      - 'https://8.8.8.8/dns-query#h3=true'
    nameserver:
    - 'https://223.6.6.6/dns-query#h3=true'
    fallback:
    - 'https://8.8.8.8/dns-query#proxy&h3=true'
    proxy-server-nameserver:
    - https://101.6.6.6:8443/dns-query
    fallback-filter:
      geoip: false
      geoip-code: CN
      ipcidr:
      - 240.0.0.0/4
    fake-ip-filter:
    - +.lan
    - +.microsoft*.com
    - localhost.ptlogin2.qq.com
TEST_URL: http://www.msftconnecttest.com/connecttest.txt

RULESET:
- - OpenAI
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/ChatBot.list
- - Telegram
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Telegram.list
- - G/M
  - https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/google-cn.list
  - https://ruleset.skk.moe/Clash/non_ip/microsoft.txt
- - X/Meta
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitter.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Facebook.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Instagram.list
- - Spotify
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Spotify.list
- - Ads
  - https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-QuantumultX.list
- - Bypass
  - https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
  - '[]GEOIP,CN'
- - Others
  - '[]FINAL'
CUSTOM_PROXY_GROUP:
- name: Common
  type: select
  rule: false
  prior: PROXY
- name: Telegram
  type: select
  regex: 🇭🇰|🇸🇬
- name: X/Meta
  type: select
  regex: 🇹🇼
- name: G/M
  type: select 
  regex: 🇺🇸
- name: Spotify 
  type: select 
  regex: 🇹🇼
- name: OpenAI
  type: select
  regex: 日本原生-IEPL
- name: Others
  type: select 
  prior:PROXY
- name: Ads
  type: select 
  prior: REJECT
- name: Bypass
  type: select 
  prior: DIRECT
